os: linux
sudo: required
dist: xenial
language: generic

branches:
  only: 
    - master
    - dev
    - /^hotfix.*$/

before_install:
  - sudo systemctl mask apt-daily.service
  - sudo systemctl mask apt-daily.timer
  - sudo systemctl mask apt-daily-upgrade.service
  - sudo systemctl mask apt-daily-upgrade.timer
  - sudo apt-get update -qq
  - sudo apt-get remove -y postgresql*
  - sudo apt-get upgrade -qq --allow-unauthenticated

script:
  - sh -e ./step0.bash
  - sh -e ./step1.bash
